# Generated by Django 4.1.1 on 2023-01-01 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Категория")),
                (
                    "beds_count",
                    models.IntegerField(verbose_name="Количество спальных мест"),
                ),
                (
                    "people_count",
                    models.IntegerField(verbose_name="Количество человек"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер комнаты")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hotel_rooms.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Номер",
                "verbose_name_plural": "Номера",
                "ordering": ("number",),
            },
        ),
    ]
