# Generated by Django 4.1.1 on 2023-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0002_remove_rooms_description_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Тип номера', 'verbose_name_plural': 'Типы номеров'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='facilities',
            field=models.CharField(default='Wi-Fi, ТВ, Душ, Кондиционер', max_length=200, verbose_name='Удобства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ночь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='size',
            field=models.IntegerField(default=50, verbose_name='Размер комнаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='Стандарт', max_length=150, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
