# Generated by Django 4.1.1 on 2023-04-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0003_alter_category_options_remove_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mainphoto',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_rooms.category', verbose_name='ID категории')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
