# Generated by Django 4.1.1 on 2023-05-13 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_rooms', '0004_category_mainphoto_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mainphoto',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_rooms.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_from', models.DateField(verbose_name='С')),
                ('booked_to', models.DateField(verbose_name='До')),
                ('guests', models.IntegerField(verbose_name='Количество ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_rooms.category', verbose_name='Категория')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_rooms.rooms', verbose_name='Номер комнаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
