# Generated by Django 4.1.1 on 2023-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0006_alter_reservation_guests_reservationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(blank=True, default=1, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='reservationhistory',
            name='price',
            field=models.IntegerField(blank=True, default=1, verbose_name='Цена'),
        ),
    ]
